%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.1.9

-ifndef(code_unloading).
-define(code_unloading, true).

-define(code_unloading_gpb_version, "4.1.9").

-ifndef('CMSTOREMODULE_PB_H').
-define('CMSTOREMODULE_PB_H', true).
-record('CmStoreModule',
        {module                 :: iodata(),        % = 1
         binary                 :: iodata(),        % = 2
         filepath               :: iodata()         % = 3
        }).
-endif.

-ifndef('RESPONSE_PB_H').
-define('RESPONSE_PB_H', true).
-record('Response',
        {error                  :: boolean() | 0 | 1, % = 1
         type                   :: 'ATOM' | 'STRING' | 'TUPLE' | integer(), % = 2, enum ResponseType
         message                :: iodata()         % = 3
        }).
-endif.

-ifndef('CMREMOTEPROCEDURECALL_PB_H').
-define('CMREMOTEPROCEDURECALL_PB_H', true).
-record('CmRemoteProcedureCall',
        {module                 :: iodata(),        % = 1
         function               :: iodata(),        % = 2
         args = []              :: [iodata()] | undefined % = 3
        }).
-endif.

-endif.
